### ISSUE TITLE
ResourceWarning in example_benchmark.py

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#355]
https://travis-ci.com/github/atmos-cloud-sim-uj/PySDM/jobs/469418709#L2465

```
The command python -We PySDM_examples/Arabas_et_al_2015_Figs_8_9/example_benchmark.py exited with 0.

Log:

0.0% (times since last print: cpu=1.0s wall=0.9s)
...
100.0% (times since last print: cpu=0.1s wall=0.1s)

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/weakref.py", line 642, in _exitfunc

    f()

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/weakref.py", line 566, in __call__

    return info.func(*info.args, **(info.kwargs or {}))

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/tempfile.py", line 816, in _cleanup

    _warnings.warn(warn_message, ResourceWarning)

ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpwhvekbny'>

/home/travis/.travis/functions: line 607:  4149 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"

PySDM_examples/Arabas_et_al_2015_Figs_8_9/example.py
```

**Comment by slayoo** [comment]
silenced: https://github.com/atmos-cloud-sim-uj/PySDM/pull/402/commits/8c22927abd9457272775898f0593fb2b4ba3055f
