### ISSUE TITLE
sort out PytestUnraisableExceptionWarning (ResourceWarning: Implicitly cleaning up <TemporaryDirectory...) in test_spin_up

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDM#404]
e.g.:
https://ci.appveyor.com/project/slayoo/pysdm/builds/37770879/job/pf4u1d5wdp9hpg4p
```
    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <finalize object at 0x1188d090; dead>
E               
E               Traceback (most recent call last):
E                 File "C:\Python38\lib\weakref.py", line 566, in __call__
E                   return info.func(*info.args, **(info.kwargs or {}))
E                 File "C:\Python38\lib\tempfile.py", line 816, in _cleanup
E                   _warnings.warn(warn_message, ResourceWarning)
E               ResourceWarning: Implicitly cleaning up <TemporaryDirectory 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmprs5cgqf5'>
```

**Comment by slayoo** [comment]
silenced: https://github.com/atmos-cloud-sim-uj/PySDM/pull/402/commits/8c22927abd9457272775898f0593fb2b4ba3055f
